// packages/create-fate/templates/fate/_shared/vue-app/src/ui/Section.vue
<script setup lang="ts">
import { computed } from 'vue';
import cx from '../lib/cx.ts';

const props = defineProps<{
  class?: string;
  gap?: number;
}>();

const classes = computed(() =>
  cx('container mx-auto flex max-w-5xl flex-col px-4 py-6 lg:px-8 lg:py-10', props.class),
);
</script>

<template>
  <section :class="classes" :style="{ gap: `${gap ?? 16}px` }">
    <slot />
  </section>
</template>

// client/src/ui/Section.tsx
import { VStack } from '@nkzw/stack';
import { ReactNode } from 'react';
import cx from '../lib/cx.tsx';

export default function Section({
  children,
  className,
}: {
  children: ReactNode;
  className?: string;
}) {
  return (
    <section className="px-4 py-8">
      <VStack className={cx('container mx-auto max-w-4xl', className)} gap>
        {children}
      </VStack>
    </section>
  );
}
