// example/client-preact/src/pages/CategoryPage.tsx
import { useRequest } from 'preact-fate';
import { useRoute } from 'preact-iso/router';
import CategoryCard, { CategoryView } from '../ui/CategoryCard.tsx';
import Section from '../ui/Section.tsx';

export default function CategoryPage() {
  const { id } = useRoute().params as { id?: string };

  if (!id) {
    throw new Error('fate: Category ID is required.');
  }

  const { category } = useRequest(
    { category: { id, view: CategoryView } },
    { mode: 'stale-while-revalidate' },
  );

  return (
    <Section>
      <CategoryCard category={category} />
    </Section>
  );
}

// example/client-vue/src/pages/CategoryPage.vue
<script setup lang="ts">
import { useRequest } from 'vue-fate';
import { CategoryView } from '../fateViews.ts';
import { route } from '../router.ts';
import CategoryCard from '../ui/CategoryCard.vue';
import Section from '../ui/Section.vue';

if (route.value.name !== 'category') {
  throw new Error('fate: Category ID is required.');
}

const { category } = await useRequest(
  { category: { id: route.value.params.id, view: CategoryView } },
  { mode: 'stale-while-revalidate' },
).ready();
</script>

<template>
  <Section>
    <CategoryCard :category="category" />
  </Section>
</template>
