// example/client-preact/src/pages/PostPage.tsx
import { useRequest } from 'preact-fate';
import { useRoute } from 'preact-iso/router';
import { PostCard, PostView } from '../ui/PostCard.tsx';
import Section from '../ui/Section.tsx';

export default function PostPage() {
  const { id } = useRoute().params as { id?: string };

  if (!id) {
    throw new Error('fate: Post ID is required.');
  }

  const { post } = useRequest({ post: { id, view: PostView } });

  return (
    <Section>
      <PostCard detail post={post} />
    </Section>
  );
}

// example/client-vue/src/pages/PostPage.vue
<script setup lang="ts">
import { useRequest } from 'vue-fate';
import { PostView } from '../fateViews.ts';
import { route } from '../router.ts';
import PostCard from '../ui/PostCard.vue';
import Section from '../ui/Section.vue';

if (route.value.name !== 'post') {
  throw new Error('fate: Post ID is required.');
}

const { post } = await useRequest({
  post: { id: route.value.params.id, view: PostView },
}).ready();
</script>

<template>
  <Section>
    <PostCard detail :post="post" />
  </Section>
</template>
