// packages/create-fate/templates/fate/_shared/vue-app/pages/index.vue
<script setup lang="ts">
import { useListView, useRequest } from 'vue-fate';
import { PostView, UserView } from '../src/fateViews.ts';
import Button from '../src/ui/Button.vue';
import Card from '../src/ui/Card.vue';
import PostCard from '../src/ui/PostCard.vue';
import Section from '../src/ui/Section.vue';
import UserCard from '../src/ui/UserCard.vue';

const PostConnectionView = {
  args: { first: 10 },
  items: {
    node: PostView,
  },
  pagination: {
    hasNext: true,
  },
};

const request = useRequest({
  posts: { list: PostConnectionView },
  viewer: { view: UserView },
});
const { posts: postsRef, viewer } = await request.ready();
const [posts, loadNext] = useListView(PostConnectionView, postsRef);
</script>

<template>
  <Section :gap="32">
    <div class="grid gap-8 lg:grid-cols-[1.6fr_1fr] lg:items-stretch">
      <Card class="border border-white/20 bg-linear-to-r from-blue-500 to-sky-500 text-white">
        <div class="space-y-3">
          <p class="text-xs font-semibold tracking-widest uppercase">
            <span class="lowercase italic">fate</span> demo
          </p>
          <h1 class="text-3xl leading-tight font-semibold text-balance lg:text-4xl">
            fate is a modern data client for Vue inspired by Relay and GraphQL.
          </h1>
          <p class="text-sm text-white/80 lg:text-base">
            This template uses Vue-native fate composables, normalized caching, data masking, and
            type-safe data fetching.
          </p>
        </div>
      </Card>
      <UserCard v-if="viewer" :viewer="viewer" />
    </div>
    <div v-if="posts.length" class="flex flex-col gap-4">
      <h2 class="pl-5 text-2xl font-semibold tracking-tight">Latest posts</h2>
      <div class="flex flex-col gap-4">
        <PostCard v-for="{ node } in posts" :key="node.id" :post="node" />
      </div>
      <div v-if="loadNext" class="flex justify-center">
        <Button :action="loadNext" variant="ghost">Load more posts</Button>
      </div>
    </div>
  </Section>
</template>

// packages/create-fate/templates/fate/void/pages/index.tsx
import Stack, { VStack } from '@nkzw/stack';
import { Link, useShared } from '@void/react';
import { CircleMinus, CirclePlus } from 'lucide-react';
import { Activity, useState } from 'react';
import { ConnectionRef, useListView, useRequest, ViewRef } from 'react-fate';
import cx from '../src/lib/cx.tsx';
import type { SharedData } from '../src/lib/shared.ts';
import { Button } from '../src/ui/Button.tsx';
import Card from '../src/ui/Card.tsx';
import CategoryCard, { CategoryView } from '../src/ui/CategoryCard.tsx';
import CreatePost from '../src/ui/CreatePost.tsx';
import EventCard, { EventView } from '../src/ui/EventCard.tsx';
import H2 from '../src/ui/H2.tsx';
import { PostCard, PostView } from '../src/ui/PostCard.tsx';
import Section from '../src/ui/Section.tsx';
import UserCard, { UserCardView } from '../src/ui/UserCard.tsx';

const PostConnectionView = {
  args: { first: 3 },
  items: {
    node: PostView,
  },
  pagination: {
    hasNext: true,
  },
};

const PostFeed = ({
  posts: postsRef,
  user,
}: {
  posts: ConnectionRef<'Post'>;
  user: ViewRef<'User'> | null;
}) => {
  const [showPostEditor, setShowPostEditor] = useState(false);
  const [posts, loadNext] = useListView(PostConnectionView, postsRef);

  return posts.length ? (
    <VStack gap={16}>
      <Stack alignCenter between gap={16}>
        <H2 className="pl-5">Latest posts</H2>
        <div>
          <button
            className={cx(
              'pr-5',
              user ? 'active:translate-y-0.5 active:opacity-50' : 'pointer-events-none opacity-0',
            )}
            onClick={() => setShowPostEditor((showPostEditor) => !showPostEditor)}
            type="button"
          >
            {showPostEditor ? (
              <CircleMinus className="h-6 w-6" />
            ) : (
              <CirclePlus className="h-6 w-6" />
            )}
          </button>
        </div>
      </Stack>
      <VStack gap={32}>
        <Activity mode={showPostEditor ? 'visible' : 'hidden'}>
          <CreatePost user={user} />
        </Activity>
        {posts.map(({ node }) => (
          <PostCard key={node.id} post={node} />
        ))}
        {loadNext ? (
          <Stack center>
            <Button onClick={loadNext} variant="ghost">
              Load more posts
            </Button>
          </Stack>
        ) : null}
      </VStack>
    </VStack>
  ) : null;
};

const CategoryFeed = ({ categories }: { categories: Array<ViewRef<'Category'>> }) =>
  categories.length ? (
    <VStack gap={16}>
      <H2 className="pl-5">Explore by theme</H2>
      <VStack gap={24}>
        {categories.map((category) => (
          <CategoryCard category={category} key={category.id} />
        ))}
      </VStack>
    </VStack>
  ) : null;

const EventFeed = ({ events }: { events: Array<ViewRef<'Event'>> }) =>
  events.length ? (
    <VStack gap={16}>
      <H2 className="pl-5">Events</H2>
      <VStack gap={24}>
        {events.map((event) => (
          <EventCard event={event} key={event.id} />
        ))}
      </VStack>
    </VStack>
  ) : null;

export default function HomePage() {
  const { auth } = useShared<SharedData>();
  const user = auth.user;
  const { categories, events, posts, viewer } = useRequest({
    categories: { list: CategoryView },
    events: { list: EventView },
    posts: { list: PostConnectionView },
    viewer: { view: UserCardView },
  });

  return (
    <Section gap={32}>
      <div className={cx('grid gap-8 lg:items-stretch', user ? 'lg:grid-cols-[1.6fr_1fr]' : '')}>
        <Card className="border border-white/20 bg-linear-to-r from-blue-500 to-sky-500 text-white dark:from-blue-600 dark:to-sky-600">
          <Stack alignCenter gap={12} wrap>
            <span className="squircle bg-white/20 px-2 py-1 text-xs font-semibold tracking-widest uppercase">
              <span className="lowercase italic">fate</span> demo
            </span>
          </Stack>
          <div className="space-y-3">
            <h1 className="text-3xl leading-tight font-semibold text-balance lg:text-4xl">
              fate is a modern data client for React inspired by Relay and GraphQL.
            </h1>
            <p className="text-sm text-white/80 lg:text-base">
              fate combines view composition, normalized caching, data masking, Async React
              features, and type-safe data fetching.
            </p>
          </div>
          <Stack alignCenter gap={12} wrap>
            {!user && (
              <>
                <Button asChild size="sm" variant="secondary">
                  <Link className="squircle px-4 py-2 text-sm font-semibold" href="/login">
                    Login
                  </Link>
                </Button>
                <span className="text-sm text-white/80">Sign in to post comments.</span>
              </>
            )}
          </Stack>
        </Card>
        {viewer && <UserCard viewer={viewer} />}
      </div>
      <div className="grid gap-8 lg:grid-cols-[1.6fr_1fr] lg:items-start">
        <PostFeed posts={posts} user={viewer} />
        <VStack gap={24}>
          <CategoryFeed categories={categories} />
          <EventFeed events={events} />
        </VStack>
      </div>
    </Section>
  );
}
