// packages/create-fate/templates/fate/void/pages/category/[id].tsx
import { useRequest } from 'react-fate';
import CategoryCard, { CategoryView } from '../../src/ui/CategoryCard.tsx';
import Section from '../../src/ui/Section.tsx';
import type { Props } from './[id].server.ts';

export default function CategoryPage({ id }: Props) {
  if (!id) {
    throw new Error('fate: Category ID is required.');
  }

  const { category } = useRequest(
    { category: { id, view: CategoryView } },
    { mode: 'stale-while-revalidate' },
  );

  return (
    <Section>
      <CategoryCard category={category} />
    </Section>
  );
}

// packages/create-fate/templates/fate/_shared/vue-app/pages/post/[id].vue
<script setup lang="ts">
import { useParams } from '@void/vue';
import { useRequest } from 'vue-fate';
import { PostView } from '../../src/fateViews.ts';
import PostCard from '../../src/ui/PostCard.vue';
import Section from '../../src/ui/Section.vue';

const params = useParams<{ id: string }>();
const id = params.id;

if (!id) {
  throw new Error('fate: Post ID is required.');
}

const { post } = await useRequest({
  post: { id, view: PostView },
}).ready();
</script>

<template>
  <Section>
    <PostCard :post="post" />
  </Section>
</template>
