// example/client-vue/src/pages/LoginPage.vue
<script setup lang="ts">
import { ExternalLinkIcon } from '@lucide/vue';
import { onMounted, ref } from 'vue';
import { visit } from '../router.ts';
import Button from '../ui/Button.vue';
import Card from '../ui/Card.vue';
import H2 from '../ui/H2.vue';
import Input from '../ui/Input.vue';
import Section from '../ui/Section.vue';
import AuthClient from '../user/AuthClient.ts';

const email = ref('');
const password = ref('');
const session = AuthClient.useSession();

const signIn = async () => {
  await AuthClient.signIn.email(
    {
      email: email.value,
      password: password.value,
    },
    {
      onError: () => {},
      onRequest: () => {},
      onSuccess: async () => {
        await session.value.refetch();
        visit('/', { replace: true });
      },
    },
  );
};

onMounted(() => {
  if (session.value.data) {
    visit('/', { replace: true });
  }
});
</script>

<template>
  <Section v-if="!session.data">
    <div class="flex flex-col items-center gap-4">
      <H2 class="pl-5">Sign In</H2>
      <div class="flex flex-wrap gap-8">
        <Card class="w-84">
          <form class="flex flex-col gap-3" @submit.prevent="signIn">
            <Input v-model="email" class="w-48" name="email" placeholder="email" type="email" />
            <Input
              v-model="password"
              class="w-48"
              name="password"
              placeholder="password"
              type="password"
            />
            <div>
              <Button type="submit" variant="outline">Sign In</Button>
            </div>
          </form>
        </Card>
        <Card class="w-84">
          <p>
            Try one of the
            <a
              class="inline-flex items-center gap-1 px-1 underline hover:no-underline"
              href="https://github.com/nkzw-tech/fate/blob/main/example/seedData.ts#L1"
              rel="noreferrer"
              target="_blank"
            >
              Example Accounts
              <ExternalLinkIcon class="h-4 w-4" />
            </a>
            in the seed data.
          </p>
        </Card>
      </div>
    </div>
  </Section>
</template>

// example/client-preact/src/pages/LoginPage.tsx
import { ExternalLinkIcon } from 'lucide-preact';
import { useLocation } from 'preact-iso/router';
import { useEffect, useState } from 'preact/hooks';
import { Form, useActionState } from '../lib/actions.tsx';
import { AsyncButton } from '../ui/Button.tsx';
import Card from '../ui/Card.tsx';
import H2 from '../ui/H2.tsx';
import Input from '../ui/Input.tsx';
import Section from '../ui/Section.tsx';
import Stack, { VStack } from '../ui/Stack.tsx';
import AuthClient from '../user/AuthClient.ts';

export default function LoginPage() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const { route } = useLocation();
  const { data: session } = AuthClient.useSession();

  // void's `router.flushAll()` drops its page-data cache before navigating;
  // preact-iso has no such cache, so navigating is all that's left.
  const [, signInAction] = useActionState(async () => {
    await AuthClient.signIn.email(
      {
        email,
        password,
      },
      {
        onError: () => {},
        onRequest: () => {},
        onSuccess: () => {
          route('/', true);
        },
      },
    );

    return null;
  }, null);

  useEffect(() => {
    if (session) {
      route('/', true);
    }
  }, [route, session]);

  if (session) {
    return null;
  }

  return (
    <Section>
      <VStack center gap={16}>
        <H2 className="pl-5">Sign In</H2>
        <Stack gap={32} wrap>
          <Card className="w-84">
            <Stack gap vertical>
              <VStack action={signInAction} as={Form} gap={12}>
                <Input
                  className="w-48"
                  name="email"
                  onInput={(e) => setEmail(e.currentTarget.value)}
                  placeholder="email"
                  type="email"
                  value={email}
                />
                <Input
                  className="w-48"
                  name="password"
                  onInput={(e) => setPassword(e.currentTarget.value)}
                  placeholder="password"
                  type="password"
                  value={password}
                />
                <div>
                  <AsyncButton type="submit" variant="outline">
                    Sign In
                  </AsyncButton>
                </div>
              </VStack>
            </Stack>
          </Card>
          <Card className="w-84">
            <p>
              Try one of the
              <Stack
                alignCenter
                as="a"
                className="inline-flex! px-1 underline hover:no-underline"
                gap={4}
                href="https://github.com/nkzw-tech/fate/blob/main/example/seedData.ts#L1"
                rel="noreferrer"
                target="_blank"
              >
                Example Accounts
                <ExternalLinkIcon className="h-4 w-4" />
              </Stack>{' '}
              in the seed data.
            </p>
          </Card>
        </Stack>
      </VStack>
    </Section>
  );
}
