// example/client/src/ui/EventCard.tsx
import type { Event, EventAttendee } from '@nkzw/fate-server/src/trpc/views.ts';
import Stack, { VStack } from '@nkzw/stack';
import { ArrowUpRight, CalendarDays, MapPin, Users } from 'lucide-react';
import { useView, view, ViewRef } from 'react-fate';
import formatLabel from '../lib/formatLabel.tsx';
import { Badge } from '../ui/Badge.tsx';
import Card from '../ui/Card.tsx';
import { UserView } from '../ui/UserCard.tsx';

const EventAttendeeView = view<EventAttendee>()({
  id: true,
  notes: true,
  status: true,
  user: UserView,
});

export const EventView = view<Event>()({
  attendees: {
    items: {
      node: EventAttendeeView,
    },
  },
  attendingCount: true,
  capacity: true,
  description: true,
  endAt: true,
  host: UserView,
  id: true,
  livestreamUrl: true,
  location: true,
  name: true,
  startAt: true,
  topics: true,
  type: true,
});

const EventAttendeeChip = ({ attendee: attendeeRef }: { attendee: ViewRef<'EventAttendee'> }) => {
  const attendee = useView(EventAttendeeView, attendeeRef);
  const user = useView(UserView, attendee.user);

  return (
    <Badge className="text-nowrap" key={attendee.id} variant="outline">
      {user?.name ?? 'Guest'} · {formatLabel(attendee.status)}
    </Badge>
  );
};

const intlFormatDateTime = new Intl.DateTimeFormat(undefined, {
  day: 'numeric',
  hour: 'numeric',
  minute: 'numeric',
  month: 'short',
});

const formatDateTime = (date: string) => intlFormatDateTime.format(new Date(date));

export default function EventCard({ event: eventRef }: { event: ViewRef<'Event'> }) {
  const event = useView(EventView, eventRef);
  const host = useView(UserView, event.host);
  const attendees = event.attendees?.items ?? [];
  const topics = event.topics ?? [];

  return (
    <Card key={event.id}>
      <VStack gap={12}>
        <Stack alignCenter between gap={12}>
          <div>
            <h4 className="text-base font-semibold text-foreground">{event.name}</h4>
            <p className="text-sm text-muted-foreground">{event.description}</p>
          </div>
          <Badge className="text-nowrap" variant="secondary">
            {formatLabel(event.type)}
          </Badge>
        </Stack>
        <Stack alignCenter gap>
          <CalendarDays className="text-muted-foreground" size={14} />
          <span className="text-sm text-foreground/80">
            {formatDateTime(event.startAt)} → {formatDateTime(event.endAt)}
          </span>
        </Stack>
        <Stack alignCenter gap>
          <MapPin className="text-muted-foreground" size={14} />
          <span className="text-sm text-foreground/80">{event.location}</span>
        </Stack>
        <Stack alignCenter gap>
          <Users className="text-muted-foreground" size={14} />
          <span className="text-sm text-foreground/80">
            {event.attendingCount ?? attendees.length} attending · capacity {event.capacity}
          </span>
        </Stack>
        <Stack alignCenter gap>
          <ArrowUpRight className="text-muted-foreground" size={14} />
          <span className="text-sm text-foreground/80">Hosted by {host?.name ?? 'Unknown'}</span>
        </Stack>
        {topics.length ? (
          <Stack gap wrap>
            {topics.map((topic) => (
              <Badge className="text-nowrap" key={topic} variant="outline">
                {topic}
              </Badge>
            ))}
          </Stack>
        ) : null}
        {attendees.length ? (
          <VStack gap>
            <span className="text-xs text-muted-foreground">Community RSVPs</span>
            <Stack gap wrap>
              {attendees.slice(0, 4).map(({ node }) => (
                <EventAttendeeChip attendee={node} key={node.id} />
              ))}
            </Stack>
          </VStack>
        ) : null}
        {event.livestreamUrl ? (
          <a
            className="text-primary text-sm font-medium hover:underline"
            href={event.livestreamUrl}
            rel="noreferrer"
            target="_blank"
          >
            Join livestream
          </a>
        ) : null}
      </VStack>
    </Card>
  );
}

// example/client-vue/src/ui/EventCard.vue
<script setup lang="ts">
import { ArrowUpRight, CalendarDays, MapPin, Users } from '@lucide/vue';
import { defineComponent, h, type PropType } from 'vue';
import type { ViewRef } from 'vue-fate';
import { useView } from 'vue-fate';
import { EventAttendeeView, EventView, UserView } from '../fateViews.ts';
import formatLabel from '../lib/formatLabel.ts';
import Badge from './Badge.vue';
import Card from './Card.vue';

const props = defineProps<{
  event: ViewRef<'Event'>;
}>();

const event = useView(EventView, () => props.event);
const host = useView(UserView, () => event.value?.host ?? null);

const intlFormatDateTime = new Intl.DateTimeFormat(undefined, {
  day: 'numeric',
  hour: 'numeric',
  minute: 'numeric',
  month: 'short',
});

const formatDateTime = (date: string) => intlFormatDateTime.format(new Date(date));

const EventAttendeeChip = defineComponent({
  name: 'EventAttendeeChip',
  props: {
    attendee: {
      required: true,
      type: Object as PropType<ViewRef<'EventAttendee'>>,
    },
  },
  setup(props) {
    const attendee = useView(EventAttendeeView, () => props.attendee);
    const user = useView(UserView, () => attendee.value?.user ?? null);

    return () =>
      attendee.value
        ? h(
            Badge,
            { class: 'text-nowrap', variant: 'outline' },
            {
              default: () =>
                `${user.value?.name ?? 'Guest'} · ${formatLabel(attendee.value?.status ?? '')}`,
            },
          )
        : null;
  },
});
</script>

<template>
  <Card v-if="event" :key="event.id">
    <div class="flex flex-col gap-3">
      <div class="flex items-center justify-between gap-3">
        <div>
          <h4 class="text-base font-semibold text-foreground">{{ event.name }}</h4>
          <p class="text-sm text-muted-foreground">{{ event.description }}</p>
        </div>
        <Badge class="text-nowrap" variant="secondary">{{ formatLabel(event.type) }}</Badge>
      </div>
      <div class="flex items-center gap-2">
        <CalendarDays class="text-muted-foreground" :size="14" />
        <span class="text-sm text-foreground/80">
          {{ formatDateTime(event.startAt) }} -> {{ formatDateTime(event.endAt) }}
        </span>
      </div>
      <div class="flex items-center gap-2">
        <MapPin class="text-muted-foreground" :size="14" />
        <span class="text-sm text-foreground/80">{{ event.location }}</span>
      </div>
      <div class="flex items-center gap-2">
        <Users class="text-muted-foreground" :size="14" />
        <span class="text-sm text-foreground/80">
          {{ event.attendingCount ?? event.attendees?.items?.length ?? 0 }} attending · capacity
          {{ event.capacity }}
        </span>
      </div>
      <div class="flex items-center gap-2">
        <ArrowUpRight class="text-muted-foreground" :size="14" />
        <span class="text-sm text-foreground/80">Hosted by {{ host?.name ?? 'Unknown' }}</span>
      </div>
      <div v-if="event.topics?.length" class="flex flex-wrap gap-2">
        <Badge v-for="topic in event.topics" :key="topic" class="text-nowrap" variant="outline">
          {{ topic }}
        </Badge>
      </div>
      <div v-if="event.attendees?.items?.length" class="flex flex-col gap-2">
        <span class="text-xs text-muted-foreground">Community RSVPs</span>
        <div class="flex flex-wrap gap-2">
          <EventAttendeeChip
            v-for="{ node } in event.attendees.items.slice(0, 4)"
            :key="node.id"
            :attendee="node"
          />
        </div>
      </div>
      <a
        v-if="event.livestreamUrl"
        class="text-primary text-sm font-medium hover:underline"
        :href="event.livestreamUrl"
        rel="noreferrer"
        target="_blank"
      >
        Join livestream
      </a>
    </div>
  </Card>
</template>
