// example/void/src/ui/TagBadge.tsx
import { useView, view, ViewRef } from 'react-fate';
import { Tag } from '../fate/server.ts';
import { Badge } from './Badge.tsx';

export const TagView = view<Tag>()({
  description: true,
  id: true,
  name: true,
});

export default function TagBadge({ tag: tagRef }: { tag: ViewRef<'Tag'> }) {
  const tag = useView(TagView, tagRef);

  if (!tag) {
    return null;
  }

  return (
    <Badge className="bg-secondary/70 text-secondary-foreground" variant="secondary">
      #{tag.name}
    </Badge>
  );
}

// example/client-vue/src/ui/TagBadge.vue
<script setup lang="ts">
import type { ViewRef } from 'vue-fate';
import { useView } from 'vue-fate';
import { TagView } from '../fateViews.ts';
import Badge from './Badge.vue';

const props = defineProps<{
  tag: ViewRef<'Tag'>;
}>();

const tag = useView(TagView, () => props.tag);
</script>

<template>
  <Badge variant="outline">{{ tag?.name }}</Badge>
</template>
