// example/client/src/ui/UserCard.tsx
import safeParse from '@nkzw/core/safeParse.js';
import { User } from '@nkzw/fate-server/src/trpc/router.ts';
import Stack, { VStack } from '@nkzw/stack';
import { ChangeEvent, useActionState, useState } from 'react';
import { useFateClient, useView, view, ViewRef } from 'react-fate';
import { Button } from '../ui/Button.tsx';
import Card from '../ui/Card.tsx';
import AuthClient from '../user/AuthClient.tsx';
import H2 from './H2.tsx';
import Input from './Input.tsx';

export type SessionUser = {
  id?: string | null;
  name?: string | null;
  username?: string | null;
};

export const UserView = view<User>()({
  id: true,
  name: true,
  username: true,
});

export const UserCardView = view<User>()({
  email: true,
  id: true,
  name: true,
  username: true,
});

const UserNameForm = ({ user }: { user: SessionUser }) => {
  const fate = useFateClient();
  const [name, setName] = useState(user.name ?? '');
  const [error, setError] = useState<string | null>(null);

  const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
    setError(null);
    setName(event.target.value);
  };

  const [, submitAction, isPending] = useActionState(async () => {
    const id = user?.id;
    if (!id) {
      return;
    }

    const newName = name.trim();
    setName(newName);

    if (newName === user.name) {
      setError(null);
      return;
    }

    try {
      setError(null);
      await fate.mutations.user.update({
        input: { name: newName },
        optimistic: {
          id,
          username: newName,
        },
        view: UserView,
      });
      await AuthClient.updateUser({ name });
    } catch (error) {
      setError(
        (error instanceof Error &&
          error.message &&
          safeParse<Array<{ message: string }>>(error.message)?.[0]?.message) ||
          'Failed to update user name.',
      );
    }
  }, null);

  const trimmedName = name.trim();
  const originalName = user.name ?? '';
  const isSaveDisabled = !user.id || !trimmedName || trimmedName === originalName || isPending;

  return (
    <div>
      <VStack action={submitAction} as="form" gap={12}>
        <h3 className="font-semibold">Update Name</h3>
        <label className="sr-only" htmlFor="header-username">
          Username
        </label>
        <Input
          aria-describedby={error ? 'header-username-error' : undefined}
          aria-invalid={error ? 'true' : undefined}
          className="w-48"
          disabled={isPending}
          id="header-username"
          name="name"
          onChange={handleChange}
          placeholder="Name"
          title={error ?? undefined}
          value={name}
        />
        <div>
          <Button disabled={isSaveDisabled} size="sm" type="submit" variant="secondary">
            Save
          </Button>
        </div>
      </VStack>
      {error ? <span id="header-username-error">{error}</span> : null}
    </div>
  );
};

export default function UserCard({ viewer: viewerRef }: { viewer: ViewRef<'User'> }) {
  const viewer = useView(UserCardView, viewerRef);

  return (
    <Card>
      <VStack between className="h-full" gap={16}>
        <VStack gap={16}>
          <H2>Your account</H2>
          <Stack alignCenter between gap={16}>
            <p className="text-sm text-muted-foreground">
              Signed in as {viewer.name}
              {viewer.email ? ` <${viewer.email}>` : null}.
            </p>
          </Stack>
        </VStack>
        <UserNameForm user={viewer} />
      </VStack>
    </Card>
  );
}

// example/client-vue/src/ui/UserCard.vue
<script setup lang="ts">
import safeParse from '@nkzw/core/safeParse.js';
import { computed, ref, watch } from 'vue';
import type { ViewRef } from 'vue-fate';
import { useFateClient, useView } from 'vue-fate';
import { UserCardView, UserView } from '../fateViews.ts';
import AuthClient from '../user/AuthClient.ts';
import Button from './Button.vue';
import Card from './Card.vue';
import H2 from './H2.vue';
import Input from './Input.vue';

const props = defineProps<{
  viewer: ViewRef<'User'>;
}>();

const fate = useFateClient();
const viewer = useView(UserCardView, () => props.viewer);
const name = ref('');
const error = ref<string | null>(null);
const isPending = ref(false);

watch(
  () => viewer.value?.name,
  (nextName) => {
    name.value = nextName ?? '';
  },
  { immediate: true },
);

const trimmedName = computed(() => name.value.trim());
const originalName = computed(() => viewer.value?.name ?? '');
const isSaveDisabled = computed(
  () =>
    !viewer.value?.id ||
    !trimmedName.value ||
    trimmedName.value === originalName.value ||
    isPending.value,
);

const submit = async () => {
  if (!viewer.value?.id || isSaveDisabled.value) {
    return;
  }

  const newName = trimmedName.value;
  name.value = newName;
  isPending.value = true;

  try {
    error.value = null;
    await fate.mutations.user.update({
      input: { name: newName },
      optimistic: {
        id: viewer.value.id,
        username: newName,
      },
      view: UserView,
    });
    await AuthClient.updateUser({ name: newName });
  } catch (caughtError) {
    error.value =
      (caughtError instanceof Error &&
        caughtError.message &&
        safeParse<Array<{ message: string }>>(caughtError.message)?.[0]?.message) ||
      'Failed to update user name.';
  } finally {
    isPending.value = false;
  }
};
</script>

<template>
  <Card v-if="viewer">
    <div class="flex h-full flex-col justify-between gap-4">
      <div class="flex flex-col gap-4">
        <H2>Your account</H2>
        <div class="flex items-center justify-between gap-4">
          <p class="text-sm text-muted-foreground">
            Signed in as {{ viewer.name }}{{ viewer.email ? ` <${viewer.email}>` : '' }}.
          </p>
        </div>
      </div>
      <form class="flex flex-col gap-3" @submit.prevent="submit">
        <h3 class="font-semibold">Update Name</h3>
        <label class="sr-only" for="header-username">Username</label>
        <Input
          id="header-username"
          v-model="name"
          :aria-describedby="error ? 'header-username-error' : undefined"
          :aria-invalid="error ? 'true' : undefined"
          class="w-48"
          :disabled="isPending"
          name="name"
          placeholder="Name"
          :title="error ?? undefined"
        />
        <div>
          <Button :disabled="isSaveDisabled" size="sm" type="submit" variant="secondary">
            Save
          </Button>
        </div>
        <span v-if="error" id="header-username-error">{{ error }}</span>
      </form>
    </div>
  </Card>
</template>
