// example/client-vue/src/ui/CategoryCard.vue
<script setup lang="ts">
import { defineComponent, h, type PropType } from 'vue';
import type { ViewRef } from 'vue-fate';
import { useView } from 'vue-fate';
import { CategoryPostView, CategoryView, UserView } from '../fateViews.ts';
import Badge from './Badge.vue';
import Card from './Card.vue';
import H3 from './H3.vue';
import Link from './Link.vue';
import TagBadge from './TagBadge.vue';

const props = defineProps<{
  category: ViewRef<'Category'>;
}>();

const category = useView(CategoryView, () => props.category);

const CategoryPost = defineComponent({
  name: 'CategoryPost',
  props: {
    post: {
      required: true,
      type: Object as PropType<ViewRef<'Post'>>,
    },
  },
  setup(props) {
    const post = useView(CategoryPostView, () => props.post);
    const author = useView(UserView, () => post.value?.author ?? null);

    return () =>
      post.value
        ? h('div', { class: 'flex flex-col gap-1', key: post.value.id }, [
            h('div', { class: 'flex items-center justify-between gap-3' }, [
              h(
                Link,
                { to: `/post/${post.value.id}` },
                {
                  default: () =>
                    h(
                      'span',
                      {
                        class:
                          'font-medium text-blue-600 no-underline hover:underline dark:text-blue-200',
                      },
                      post.value?.title,
                    ),
                },
              ),
              h('span', { class: 'text-xs text-muted-foreground' }, `${post.value.likes} likes`),
            ]),
            h('div', { class: 'flex flex-wrap items-center gap-2' }, [
              h(
                'span',
                { class: 'text-xs text-muted-foreground' },
                author.value?.name ? `by ${author.value.name}` : 'By an anonymous collaborator',
              ),
              ...(post.value.tags?.items ?? []).map(({ node }) =>
                h(TagBadge, { key: node.id, tag: node }),
              ),
            ]),
          ])
        : null;
  },
});
</script>

<template>
  <Card v-if="category" :key="category.id">
    <div class="flex flex-col gap-3">
      <div class="flex items-center justify-between gap-3">
        <div>
          <Link :to="`/category/${category.id}`">
            <H3>{{ category.name }}</H3>
          </Link>
          <p class="text-sm text-muted-foreground">{{ category.description }}</p>
        </div>
        <Badge class="text-nowrap" variant="outline">{{ category.postCount }} posts</Badge>
      </div>
      <div class="flex flex-col gap-3">
        <CategoryPost v-for="{ node } in category.posts?.items ?? []" :key="node.id" :post="node" />
      </div>
      <span v-if="category.posts?.pagination?.hasNext" class="text-sm text-muted-foreground">
        More posts available in this category...
      </span>
    </div>
  </Card>
</template>

// example/client-preact/src/ui/CategoryCard.tsx
import type { Category, Post } from '@nkzw/fate-server/src/trpc/views.ts';
import { useView, view, ViewRef } from 'preact-fate';
import { Badge } from '../ui/Badge.tsx';
import Card from '../ui/Card.tsx';
import Link from '../ui/Link.tsx';
import TagBadge, { TagView } from '../ui/TagBadge.tsx';
import { UserView } from '../ui/UserCard.tsx';
import H3 from './H3.tsx';
import Stack, { VStack } from './Stack.tsx';

const CategoryPostView = view<Post>()({
  author: UserView,
  id: true,
  likes: true,
  tags: {
    items: {
      node: TagView,
    },
  },
  title: true,
});

const CategoryPost = ({ post: postRef }: { post: ViewRef<'Post'> }) => {
  const post = useView(CategoryPostView, postRef);
  const author = useView(UserView, post.author);
  const tags = post.tags?.items ?? [];

  return (
    <VStack gap key={post.id}>
      <Stack alignCenter between gap={12}>
        <Link to={`/post/${post.id}`}>
          <span className="font-medium text-blue-600 no-underline hover:underline dark:text-blue-200">
            {post.title}
          </span>
        </Link>
        <span className="text-xs text-muted-foreground">{post.likes} likes</span>
      </Stack>
      <Stack alignCenter gap wrap>
        <span className="text-xs text-muted-foreground">
          {author?.name ? `by ${author.name}` : 'By an anonymous collaborator'}
        </span>
        {tags.length ? (
          <Stack gap wrap>
            {tags.map(({ node }) => (
              <TagBadge key={node.id} tag={node} />
            ))}
          </Stack>
        ) : null}
      </Stack>
    </VStack>
  );
};

export const CategoryView = view<Category>()({
  description: true,
  id: true,
  name: true,
  postCount: true,
  posts: {
    items: {
      node: CategoryPostView,
    },
    pagination: {
      hasNext: true,
      nextCursor: true,
    },
  },
});

export default function CategoryCard({ category: categoryRef }: { category: ViewRef<'Category'> }) {
  const category = useView(CategoryView, categoryRef);
  const posts = category.posts?.items ?? [];

  return (
    <Card key={category.id}>
      <VStack gap={12}>
        <Stack alignCenter between gap={12}>
          <div>
            <Link to={`/category/${category.id}`}>
              <H3>{category.name}</H3>
            </Link>
            <p className="text-sm text-muted-foreground">{category.description}</p>
          </div>
          <Badge className="text-nowrap" variant="outline">
            {category.postCount} posts
          </Badge>
        </Stack>
        <VStack gap={12}>
          {posts.map(({ node }) => (
            <CategoryPost key={node.id} post={node} />
          ))}
        </VStack>
        {category.posts?.pagination?.hasNext ? (
          <span className="text-sm text-muted-foreground">
            More posts available in this category...
          </span>
        ) : null}
      </VStack>
    </Card>
  );
}
