// example/client-vue/src/ui/Section.vue
<script setup lang="ts">
import { computed } from 'vue';
import cx from '../lib/cx.ts';

const props = defineProps<{
  class?: string;
  gap?: number;
}>();

const classes = computed(() =>
  cx('max-w-8xl container mx-auto flex flex-col px-4 py-6 lg:px-8 lg:py-10', props.class),
);
</script>

<template>
  <section :class="classes" :style="{ gap: `${gap ?? 16}px` }">
    <slot />
  </section>
</template>

// example/client-preact/src/ui/Section.tsx
import type { ComponentChildren } from 'preact';
import cx from '../lib/cx.ts';
import { type Gap, VStack } from './Stack.tsx';

export default function Section({
  children,
  className,
  gap,
}: {
  children: ComponentChildren;
  className?: string;
  gap?: Gap;
}) {
  return (
    <VStack
      as="section"
      className={cx('max-w-8xl container mx-auto px-4 py-6 lg:px-8 lg:py-10', className)}
      gap={gap}
    >
      {children}
    </VStack>
  );
}
